// Global type override for lucide-react-native
// This fixes the SVGSVGElement conflict when using Lucide icons in React Native

declare module 'lucide-react-native' {
  import { ComponentType } from 'react';

  export interface LucideProps {
    size?: number | string;
    color?: string;
    strokeWidth?: number | string;
    absoluteStrokeWidth?: boolean;
    style?: any;
  }

  export type LucideIcon = ComponentType<LucideProps>;

  export const Sparkles: LucideIcon;
  export const Zap: LucideIcon;
  export const ShieldCheck: LucideIcon;
  export const MessageSquare: LucideIcon;
  export const History: LucideIcon;
  export const Settings: LucideIcon;
  export const Send: LucideIcon;
  export const Plus: LucideIcon;
  export const ChevronDown: LucideIcon;
  export const ChevronLeft: LucideIcon;
  export const ChevronRight: LucideIcon;
  export const User: LucideIcon;
  export const Mail: LucideIcon;
  export const LogOut: LucideIcon;
  export const Key: LucideIcon;
  export const Eye: LucideIcon;
  export const EyeOff: LucideIcon;
  export const Copy: LucideIcon;
  export const Check: LucideIcon;
  export const X: LucideIcon;
  export const Trash: LucideIcon;
  export const Trash2: LucideIcon;
  export const Edit: LucideIcon;
  export const Edit2: LucideIcon;
  export const Edit3: LucideIcon;
  export const Search: LucideIcon;
  export const Filter: LucideIcon;
  export const Star: LucideIcon;
  export const Heart: LucideIcon;
  export const Share: LucideIcon;
  export const Share2: LucideIcon;
  export const RefreshCw: LucideIcon;
  export const RotateCcw: LucideIcon;
  export const StopCircle: LucideIcon;
  export const Square: LucideIcon;
  export const Clock: LucideIcon;
  export const Calendar: LucideIcon;
  export const Pin: LucideIcon;
  export const PinOff: LucideIcon;
  export const Bell: LucideIcon;
  export const BellOff: LucideIcon;
  export const Moon: LucideIcon;
  export const Sun: LucideIcon;
  export const Palette: LucideIcon;
  export const Database: LucideIcon;
  export const Shield: LucideIcon;
  export const Info: LucideIcon;
  export const AlertCircle: LucideIcon;
  export const AlertTriangle: LucideIcon;
  export const CheckCircle: LucideIcon;
  export const XCircle: LucideIcon;
  export const ThumbsUp: LucideIcon;
  export const ThumbsDown: LucideIcon;
  export const BarChart: LucideIcon;
  export const BarChart2: LucideIcon;
  export const BarChart3: LucideIcon;
  export const TrendingUp: LucideIcon;
  export const Activity: LucideIcon;
  export const Cpu: LucideIcon;
  export const Layers: LucideIcon;
  export const Layout: LucideIcon;
  export const LayoutGrid: LucideIcon;
  export const Columns: LucideIcon;
  export const FileText: LucideIcon;
  export const File: LucideIcon;
  export const Image: LucideIcon;
  export const Camera: LucideIcon;
  export const Paperclip: LucideIcon;
  export const Upload: LucideIcon;
  export const Download: LucideIcon;
  export const ExternalLink: LucideIcon;
  export const Link: LucideIcon;
  export const Globe: LucideIcon;
  export const Code: LucideIcon;
  export const Code2: LucideIcon;
  export const Terminal: LucideIcon;
  export const Wand2: LucideIcon;
  export const Brain: LucideIcon;
  export const Bot: LucideIcon;
  export const Lightbulb: LucideIcon;
  export const BookOpen: LucideIcon;
  export const Book: LucideIcon;
  export const Bookmark: LucideIcon;
  export const Tag: LucideIcon;
  export const Hash: LucideIcon;
  export const MessageCircle: LucideIcon;
  export const MessageSquarePlus: LucideIcon;
  export const Menu: LucideIcon;
  export const MoreHorizontal: LucideIcon;
  export const MoreVertical: LucideIcon;
  export const ArrowLeft: LucideIcon;
  export const ArrowRight: LucideIcon;
  export const ArrowUp: LucideIcon;
  export const ArrowDown: LucideIcon;
  export const Home: LucideIcon;
  export const Maximize2: LucideIcon;
  export const Minimize2: LucideIcon;
  export const SlidersHorizontal: LucideIcon;
  export const Sliders: LucideIcon;
  export const ToggleLeft: LucideIcon;
  export const ToggleRight: LucideIcon;
  export const Gauge: LucideIcon;
  export const Loader: LucideIcon;
  export const Loader2: LucideIcon;
  export const Wifi: LucideIcon;
  export const WifiOff: LucideIcon;
}
